#!/bin/bash

ffmpeg -f image2 -i "$1" -vf scale=900:-1:sws_dither=ed,palettegen "$2.palette.png"

ffmpeg -f image2 -framerate "$3" -i "$1" "$4.mkv"

ffmpeg -i "$4.mkv" -i "$2.palette.png" -filter_complex "fps=1.2,scale=500:-1:flags=lanczos[x];[x][1:v]paletteuse" "$4.gif"
